execute pathogen#infect()
let g:netrw_bufsettings = 'noma nomod nu nobl nowrap ro'

set nocompatible                " choose no compatibility with legacy vi
filetype plugin indent on       " load file type plugins + indentation
set encoding=utf-8
set showcmd                     " display incomplete commands

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter
set runtimepath^=~/Repos/dotfiles/vim/bundle/ctrlp.vim

set number
syntax enable
set background=dark
let g:netrw_preview   = 1
let g:netrw_liststyle = 3
let g:netrw_winsize   = 30
color slate


highlight LineNr term=NONE cterm=NONE ctermfg=White ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE
